#pragma config(Sensor, S2,     color,          sensorColorNxtFULL)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          attachMotor,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("datalogGraph")
#pragma debuggerWindows("debugStream")
#define MAX_COMMAND_LENGTH 50
#define RADIUS_OF_ROBOT 80
#define RADIUS_OF_WHEEL 21
#include "Headers/MyHeaders.h"


void createCommands()
{
	bot.index = 0;

	for(int i = 0; i < 4; i++)
	{
		initMoveByDegreeData(distanceToDegrees(100), distanceToDegrees(100), Acc, Acc);

			initMoveByDegreeData(100,100,Acc,Acc, true);
			initMoveByDegreeData(-100,-100,Acc,Acc, true);
			initMoveByDegreeData(100,100,Acc,Acc, true);
			initMoveByDegreeData(-100,-100,Acc,Acc, true);
			initStopRecData();

		initMoveByDegreeData(degreesToMove(90), -degreesToMove(90), Acc, Acc);

			initMoveByDegreeData(100,100,Acc,Acc, true);
			initMoveByDegreeData(-100,-100,Acc,Acc, true);
			initMoveByDegreeData(100,100,Acc,Acc, true);
			initMoveByDegreeData(-100,-100,Acc,Acc, true);
			initStopRecData();
	}

		//initMoveByDegreeData(distanceToDegrees(250), distanceToDegrees(450), Acc, Acc);



	initStopData();

	bot.index = 0;
}
void runCommands(Bot bot)
{
	BaseCommand& command = bot.commands[bot.index];
	switch(command.commandType)
	{
		case AttachMotorRec:
		{
			MoveAttachMotorData data;

			memcpy(&data, command, sizeof(MoveAttachMotorData));

			configure(data);

			if(!hasRan(data)) return;

			cleanup(data);

			finalize();


		}
		break;

		case MoveByDegreesRec:
		{
			RobotDrivetrainData data;

			memcpy(&data, command, sizeof(RobotDrivetrainData));

			configure(data);



			if(!hasRan(data)) return;

			cleanup(data);

			finalize();




		}
		break;

		/*
***********************************************		Your commands are being created while finalize is running *********************************************************************
		*/

		case LineFollowRec:
		{
			LineFollowData data;

			memcpy(&data, command, sizeof(LineFollowData));

			configure(data);

			if(!hasRan(data)) return;

			cleanup(&(LineFollowData)command);

			finalize();


		}
		break;

		case LineFollow:
		{
			LineFollowData data;

			memcpy(&data, command, sizeof(LineFollowData));

			configure(data);

			if(!hasRan(data)) return;

			cleanup(&(LineFollowData)command);

			finalize();

		}
		break;

		case AttachMotor:
		{
			MoveAttachMotorData data;

			memcpy(&data, command, sizeof(MoveAttachMotorData));

			configure(data);

			if(!hasRan(data)) return;

			cleanup(data);

			finalize();


		}
		break;

		case MoveByDegrees:
		{
			if(initiateStall(bot.left)||
			initiateStall(bot.right)||
			initiateStall(bot.center))
			{
				bot.isRecovery = true;
				writeDebugStreamLine("Recovery");
			}

			RobotDrivetrainData data;

			memcpy(&data, command, sizeof(RobotDrivetrainData));

			configure(data);

			if(!hasRan(data)) return;

			cleanup(data);

			finalize();
		}
		break;

		case StopRecovery:
		{
			bot.isRecovery = false;
		}
		break;

		case Stop:
		{
			motor[leftMotor] = 0;
			motor[rightMotor] = 0;
			displayTextLine(7, "Stopped");
		}
		break;
	}

}
void RecoveryChecker(bool& isCheckForRecovery, int startindex, int endindex)
{
	if(bot.index >= startindex && bot.index <= endindex)
	{
		isCheckForRecovery = true;
	}
	else
	{
		isCheckForRecovery = false;
	}
}


task main()
{

	bot.left.profile.previousPosition = 0;
	bot.right.profile.previousPosition = 0;
	bot.center.profile.previousPosition = 0;

	time1[T1] = 0;
	time1[T2] = 0;
	time1[T3] = 0;
	bot.isCheckForRecovery = false;
	bot.isRecovery = false;
	clearDebugStream();
	createCommands();
	writeDebugStreamLine("LeftMotor:%i", leftMotor);
	writeDebugStreamLine("RightMotor: %i", rightMotor);
	writeDebugStreamLine("CenterMotor: %i", attachMotor);
	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[rightMotor] = 0;
	nMotorEncoder[attachMotor] = 0;

	while(true)
	{
		datalogAddValueWithTimeStamp(1, motor[leftMotor]);
		datalogAddValueWithTimeStamp(2, motor[rightMotor]);

		trackVelocity(bot.left);
		trackVelocity(bot.right);


		//if(SensorValue[sonar] < 24 && !bot.isRecovery && bot.isCheckForRecovery)
		//{
		//	bot.index++;
		//	//bot.isRecovery = true;
		//}

		RecoveryChecker(bot.isCheckForRecovery, 0, 40);
		displayTextLine(6, "Bot: %i", bot.index);
		runCommands(bot);
		displayTextLine(2, "IsRecovery: %i", bot.isRecovery);


		realTime();
	}


}
