#pragma config(Motor,  motorB,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma once
#define MIN_POWER 3
#define ACCELERATION_DURATION 250
#define DECELERATION_DURATION 250
#define INTERVAL 30


enum TrapStates
{
	Acc,
	Coast,
	Dcc
};

struct TrapData
{
	int previousPosition;
	short accDuration;
	short dccDuration;
	short totalDuration;
	byte maxPower;
	tMotor motorPort;
	TrapStates state;
	bool isConfigured;
}


void resetMotors()
{
	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[rightMotor] = 0;

}

bool accelerate(TrapData data)
{
	int currentPosition = abs(nMotorEncoder[data.motorPort]-data.previousPosition);
	if(abs(currentPosition) >= abs(data.accDuration))
	{
		data.previousPosition = nMotorEncoder[data.motorPort];
		return true;
	}

	int power = (abs(nMotorEncoder[data.motorPort])*(data.maxPower-MIN_POWER)/abs(data.accDuration))+MIN_POWER;

	power = power * sgn(power);

	motor[data.motorPort] = power;


	return false;
}

bool stayAtSameSpeed(TrapData data)
{
	int currentPosition = abs(nMotorEncoder[data.motorPort]-data.previousPosition)
	if(abs(currentPosition) >= abs(data.totalDuration)-abs(data.accDuration+data.dccDuration))
	{
		return true;
	}


	int power = data.maxPower;

	power = power * sgn(power);

	motor[data.motorPort] = power;



	return false;
}

bool decelerate(TrapData data)
{
	if(abs(nMotorEncoder[data.motorPort]) >= abs(data.dccDuration))
	{
		motor[data.motorPort] = 0;
		return true;
	}

	int power = (1-(abs(nMotorEncoder[data.motorPort])*(data.maxPower-MIN_POWER)/abs(data.accDuration)))+MIN_POWER;

	motor[data.motorPort] = power * sgn(power);


	return false;
}


/*
This NOT intMotorData. It is initTrapezoidalProfile.

Trap profile is very disorganized.
pull this into it's own program.
*/

bool initTrapezoidalProfileData(TrapData& data)
{
	data.accDuration = ACCELERATION_DURATION;
	data.dccDuration = DECELERATION_DURATION;
	data.maxPower = 100;
	return true;
}

void config(TrapData data)
{
	if(data.isConfigured) return;

	data.previousPosition = nMotorEncoder[leftMotor];
	if(data.totalDuration < data.accDuration + data.dccDuration)
	{
		data.accDuration = ACCELERATION_DURATION*(data.totalDuration/(ACCELERATION_DURATION+DECELERATION_DURATION));
		data.dccDuration = data.totalDuration-data.accDuration;
		data.maxPower = (data.accDuration*100/ACCELERATION_DURATION);

	}
	if(data.maxPower < MIN_POWER)
	{
		data.dccDuration = data.totalDuration;
		data.state = Dcc;
	}
	if(data.totalDuration == 0)
	{
		//smartzero
	}
	data.isConfigured = true;
}

bool runMotorData(TrapData data)
{
	config(data);
	switch(data.state)
	{
		case Acc:
		{
			bool isDone = accelerate(data);
			writeDebugStreamLine("ACC");
			if(isDone)
			{
				data.state = Coast;
			}

		}
			break;

		case Coast:
		{
			bool isDone = stayAtSameSpeed(data);
			writeDebugStreamLine("CCC");
			if(isDone)
			{
				data.state = Dcc;
			}

		}
			break;

		case Dcc:
		{
			bool isDone = decelerate(data);
			writeDebugStreamLine("DCC");
			if(isDone)
			{
				return true;
			}
		}
			break;
	}
	return false;
}

bool TrapezoidalProfileMoveByDegrees(TrapData data)
{
	bool isDone = runMotorData(data);
	if(isDone)
	{
		return true;
	}
	return false;
}
task main()
{
	time1[T3] = 0;
	TrapData data;
	data.totalDuration = 1000;
	data.motorPort = leftMotor;
	initTrapezoidalProfileData(data);
	while(true)
	{
		datalogAddValueWithTimeStamp(1, motor[leftMotor]);
		runMotorData(data);
		int mask = INTERVAL - 1;
		int timeRemainder = mask & time1[T3];
		delay(INTERVAL - timeRemainder);
	}
}
